version: '3.3'

networks:
  demo-wordpress:



services:
   wordpress:
     depends_on:
       - wordpress-db
     image: wordpress:latest
     volumes:
       - ./wordpress_files:/var/www/html
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: wordpress-db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: team@work
     networks:
       - demo-wordpress

   wordpress-db:
     image: mysql:5.7
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: team@work
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: team@work
     networks:
       - demo-wordpress
